name:                ubuntu-cve-tracker2debsecan
version:             0.1.0.0
github:              "nilp0inter/ubuntu-cve-tracker2debsecan"
license:             BSD3
author:              "Roberto Abdelkader Martínez Pérez"
maintainer:          "robertomartinezp@gmail.com"
copyright:           "2020 Roberto Abdelkader Martínez Pérez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nilp0inter/ubuntu-cve-tracker2debsecan#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- bifunctors
- bytestring
- versions
- text
- optparse-generic

library:
  source-dirs: src

executables:
  ubuntu-cve-tracker2debsecan-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ubuntu-cve-tracker2debsecan

  check-cve-file:
    main:                Main.hs
    source-dirs:         app/check
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ubuntu-cve-tracker2debsecan

tests:
  ubuntu-cve-tracker2debsecan-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ubuntu-cve-tracker2debsecan
    - hspec
    - QuickCheck
    - hspec-parsec
    - generic-random
