name:                ubuntu-cve-tracker2debsecan
version:             0.1.0
github:              "BBVA/ust2dsa"
license:             Apache-2.0
author:              "Roberto Abdelkader Martínez Pérez <robertomartinezp@gmail.com>, pancho horrillo <pancho.horrillo@bbva.com>"
maintainer:          "robertoabdelkader.martinez@bbva.com"
copyright:           "2020 Banco Bilbao Vizcaya Argentaria, S.A."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/BBVA/ust2dsa#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- bifunctors
- bytestring
- versions
- text
- cmdargs
- utility-ht
- split
- strict
- zlib

library:
  source-dirs: src

executables:
  ust2dsa:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -static
    cc-options: -static
    ld-options: -static -pthread
    extra-lib-dirs: ./.system-work/lib
    dependencies:
    - ubuntu-cve-tracker2debsecan

tests:
  ubuntu-cve-tracker2debsecan-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ubuntu-cve-tracker2debsecan
    - hspec
    - QuickCheck
    - hspec-parsec
    - generic-random
