name: Cook CVE database and publish it

on:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone data branch current repo
      uses: actions/checkout@v2
      with:
        ref: data

    - name: Reset HEAD to the first commit
      run: |
        FIRST_COMMIT=$(git log --pretty=oneline --reverse | head -n1 | awk '{ print $1 }')
        git reset --hard "${FIRST_COMMIT}"

    - name: Obtain latest release of ust2dsa
      uses: dsaltares/fetch-gh-release-asset@8cb83a34e794f747d55fd1bdc5dd7178890e4bf2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo: BBVA/ust2dsa
        version: latest
        file: ust2dsa

    - name: Install ust2dsa
      run: |
        sudo install ust2dsa /usr/local/bin/
        rm -f ust2dsa

    - name: Clone Ubuntu CVE Tracker repo
      run: |
        REPO=ubuntu-cve-tracker
        git clone --depth 1 https://git.launchpad.net/"$REPO" /tmp/"$REPO"

    - name: Run ust2dsa
      run: |
        ust2dsa                                 \
          --generic                             \
          --release=groovy                      \
          --release=focal                       \
          --release=eoan                        \
          --release=bionic                      \
          --release=xenial                      \
          --release=trusty                      \
          /tmp/ubuntu-cve-tracker/active/CVE-*

    - name: Commit and push
      run: |
        git config user.name 'Release Bot'
        git config user.email 'release-bot@lafundacion'
        git add .
        git commit --amend -m "$(date)"
        git push --force-with-lease origin data
